name: flatten_me
description: Flatten me out
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  expanded_grid: ^1.0.0
  collection: ^1.15.0
  rainbow_color: ^2.0.1
  sleek_circular_slider: ^2.0.1
  flutter_circular_slider: 
    git:
      url: https://github.com/Faiizii/flutter-circular-slider
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.18
  google_fonts: ^2.3.1
  sensors_plus:
    git:
      url: https://github.com/organic-nailer/plus_plugins.git
      path: packages/sensors_plus/sensors_plus

dependency_overrides:
  sensors_plus_web:
    git:
      url: https://github.com/organic-nailer/plus_plugins.git
      path: packages/sensors_plus/sensors_plus_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/howto1.png
    - assets/howto2.png
